/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CellarRouteImport } from './routes/cellar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindUsRouteImport } from './routes/find-us'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoryRouteImport } from './routes/story'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as VineyardRouteImport } from './routes/vineyard'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as WinesRouteImport } from './routes/wines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CellarRoute = CellarRouteImport.update({
  id: '/cellar',
  path: '/cellar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUsRoute = FindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const VineyardRoute = VineyardRouteImport.update({
  id: '/vineyard',
  path: '/vineyard',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesRoute = WinesRouteImport.update({
  id: '/wines',
  path: '/wines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cellar': typeof CellarRoute
  '/contact': typeof ContactRoute
  '/find-us': typeof FindUsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/studio': typeof StudioRoute
  '/trade': typeof TradeRoute
  '/vineyard': typeof VineyardRoute
  '/visit': typeof VisitRoute
  '/wines': typeof WinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cellar': typeof CellarRoute
  '/contact': typeof ContactRoute
  '/find-us': typeof FindUsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/studio': typeof StudioRoute
  '/trade': typeof TradeRoute
  '/vineyard': typeof VineyardRoute
  '/visit': typeof VisitRoute
  '/wines': typeof WinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cellar': typeof CellarRoute
  '/contact': typeof ContactRoute
  '/find-us': typeof FindUsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/studio': typeof StudioRoute
  '/trade': typeof TradeRoute
  '/vineyard': typeof VineyardRoute
  '/visit': typeof VisitRoute
  '/wines': typeof WinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cellar'
    | '/contact'
    | '/find-us'
    | '/shop'
    | '/story'
    | '/studio'
    | '/trade'
    | '/vineyard'
    | '/visit'
    | '/wines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cellar'
    | '/contact'
    | '/find-us'
    | '/shop'
    | '/story'
    | '/studio'
    | '/trade'
    | '/vineyard'
    | '/visit'
    | '/wines'
  id:
    | '__root__'
    | '/'
    | '/cellar'
    | '/contact'
    | '/find-us'
    | '/shop'
    | '/story'
    | '/studio'
    | '/trade'
    | '/vineyard'
    | '/visit'
    | '/wines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CellarRoute: typeof CellarRoute
  ContactRoute: typeof ContactRoute
  FindUsRoute: typeof FindUsRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  StudioRoute: typeof StudioRoute
  TradeRoute: typeof TradeRoute
  VineyardRoute: typeof VineyardRoute
  VisitRoute: typeof VisitRoute
  WinesRoute: typeof WinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellar': {
      id: '/cellar'
      path: '/cellar'
      fullPath: '/cellar'
      preLoaderRoute: typeof CellarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-us': {
      id: '/find-us'
      path: '/find-us'
      fullPath: '/find-us'
      preLoaderRoute: typeof FindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vineyard': {
      id: '/vineyard'
      path: '/vineyard'
      fullPath: '/vineyard'
      preLoaderRoute: typeof VineyardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines': {
      id: '/wines'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof WinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CellarRoute: CellarRoute,
  ContactRoute: ContactRoute,
  FindUsRoute: FindUsRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  StudioRoute: StudioRoute,
  TradeRoute: TradeRoute,
  VineyardRoute: VineyardRoute,
  VisitRoute: VisitRoute,
  WinesRoute: WinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
